name: photo_list_redux
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_rating_bar: ^3.2.0+1
  built_value: ^7.1.0
  built_collection: ^4.3.2
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  freezed_annotation: ^0.12.0
  flutter_staggered_grid_view: ^0.3.3
  url_launcher: ^5.7.10
  english_words: ^3.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  freezed: ^0.12.2

flutter:
  uses-material-design: true
